### ISSUE TITLE
Tema prace

### ISSUE THREAD

**Issue by jozefchmelar** [jozefchmelar/AdvancedDatabaseProject#1]
[zadania  semestrálnych prác 2018.pdf](https://github.com/jozefchmelar/AdvancedDatabaseProject/files/2483123/zadania.semestralnych.prac.2018.pdf)

Osobne mi pride najjednoduchsie riesit D autopozicovnu.  ..

**Comment by FilipBoros** [comment]
Za mňa súhlas, to D vyzerá najlepšie. 👍

**Comment by branopal** [comment]
Ked som to tak zhruba prebehol, to D a C vyzera asi najlepsie, kludne mozme dat D.

Co sa tyka poctu ludi, minuleho roku dovolil robit aj v menej ako v 4 ludoch a potom dal robit "menej" prace - myslite, ze to tak bude aj tento rok?

**Comment by jozefchmelar** [comment]
Opytam sa.
Zatial teda bude tema **D**

**Comment by branopal** [comment]
Zapises nas teda? Ak tam je volne miesto? Nemam na tomto PC akurat sqldeveloper tak to neviem checknut

**Comment by jozefchmelar** [comment]
ja teraz tiez nemam pristup na sqldev ale ked budem za svojim pc tak to spravim
