### ISSUE TITLE
Vystupy 

### ISSUE THREAD

**Issue by jozefchmelar** [jozefchmelar/AdvancedDatabaseProject#2]
Musime vymysliet 6 vytstupov ktore budeme implemntovat do  dalsieho cvika.

Kazdy dva

napr. pre nejaky genericky typ, existuje v nejakom rozsahu ceny nieco co je o 10% lacnejsie.

**Comment by branopal** [comment]
1. 20% najpozicavanejsich znaciek aut (napr. bmw, mercedes, ...)
2. Pocet vypozicanych aut daneho zakaznika/znacky auta/konkretneho auta pre zadane casove okno
3. Doba, za ktoru sa kazi vybrane auto (ak budeme mat historiu stavov, tak od stavu najnovsie po aktualny stav).
4. Zarobok, ktory sme ziskali od daneho zakaznika (alebo danej rodiny, resp vsetkych s danym priezviskom).

Dal som ich do istoty viac, ak by niektore boli prilis "jednoduche", tak do istoty. Co sa tretieho tyka, neviem, ci budeme robit system tak, aby mal aj historiu, ak nie, tak toto mozme zmazat.

**Comment by FilipBoros** [comment]
Za mňa takto:

1. Deň v týždni, v ktorom býva najviac výpožičiek. (môže byť za dané časové obdobie, alebo celkovo).
2. 10% vozidiel, ktoré prinášajú najväčšie výnosy. (zárobky - náklady na opravy)
3. Vozidlá, ktoré za dané časové obdobie nepriniesli žiadny výnos. (náklady na opravy, boli väčšie ako zárobky)

Tiež som dal jeden rezervný for istota :)

**Comment by jozefchmelar** [comment]
1. Zoznam najdrahsich aut na opravu 
2. Najviac vytazene obdobia v roku
3. Najporuchovejsie/najspolahlivejsie auta

**Comment by jozefchmelar** [comment]
Poslal som mu to na mail. Povedal ze by sme mohli este urobit take nieco, ze zobrat nejake auto a pozerat s ako sa menili naklady na to auto v case....ked bolo nove malo taketo naklady a ked je starsie tak ine...alebo ked to ma iny spravca...inak to zobral

Poslal som mu tieto

- 10% vozidiel, ktoré prinášajú najväčšie výnosy. (zárobky - náklady na opravy)
- Vozidlá, ktoré za dané časové obdobie nepriniesli žiadny výnos. (náklady na opravy, boli väčšie ako zárobky)
- Najviac vytazene obdobia v roku
- 20% najpozicavanejsich znaciek aut (napr. bmw, mercedes, ...)
- Najporuchovejsie/najspolahlivejsie auta
- Pocet vypozicanych aut daneho zakaznika/znacky auta/konkretneho auta pre zadane casove okno
